### ISSUE TITLE
Unexpected error message at the end of Contract Tests, when API keys absent

### ISSUE THREAD

**Issue by kunal-mohta** [kunal-mohta/fluid-adaptive-content-service#1]
I implemented a prompt and termination of Contract tests when API key(s) that are required are not present in the `.env` file.
This seems to work properly when running a single Contract test, but gives an unexpected `npm` error log at the end, when running multiple tests together, and all of them terminate due to absence of API keys.
Here is a screenshot of the error log - 
![gsoc](https://user-images.githubusercontent.com/30414954/43042998-2426ef10-8da7-11e8-818c-f67a543b7029.png)

## Steps to reproduce
- Remove the Yandex and Google API keys from the `.env` file
- Run `npm run test-translation-contract`

## Speculated reason for the error
I am checking for the API keys before registering the tests. So when the the keys are absent, no test is run, which leads to an **unexpected end** of the node file.

**Note** that the error occurs only when running multiple tests and ALL of them fail. If, for example, you were to remove Yandex keys from `.env` but keep Google ones, then there would be no error when running all translation contract tests.

**Comment by waharnum** [comment]
I've run into similar issues before when writing tests that are conditional upon things like platform features or API keys.

What I'd suggest looking at is to have the "no API key present" path do something like run a test with 0 asserts, with a message like "API key not present, tests cannot run'. (you usually have to do something like `expect(0)` to avoid complaints about this)

**Comment by kunal-mohta** [comment]
@waharnum I tried doing this with `jqUnit.expect(0)`, but got an error saying
```
FATAL ERROR: Uncaught exception: Cannot read property 'expected' of undefined
TypeError: Cannot read property 'expected' of undefined
    at F.expect (/home/kunal/node_modules/infusion/tests/lib/qunit/js/qunit.js:444:26)
    at Object.expect (/home/kunal/node_modules/infusion/tests/test-core/jqUnit/js/jqUnit.js:193:35)
    at Object.adaptiveContentService.tests.utils.checkGoogleKeys (/home/kunal/gsoc/fluid-adaptive-content-service/share/testUtils.js:134:16)
    at Object.<anonymous> (/home/kunal/gsoc/fluid-adaptive-content-service/share/translation/tests/contractTests/google/listLanguages.js:153:36)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Function.Module.runMain (module.js:684:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
```
I think this is probably because I am using jqUnit before registering any tests, but I am not sure.
Also, as the [jqUnit's page on Infusion documentation](https://docs.fluidproject.org/infusion/development/jqUnit.html#jqunitexpectcount) says, the `expect()` method accepts the number of *additional* assertions required for the test to pass. So for our purpose, this would be a negative number and not 0.

**Comment by waharnum** [comment]
Hi Kunal,

I looked into this further - it looks like jqUnit (via `kettle.loadTestingSupport()`) will complain even if you queue 0 tests.

Here's a non-optimized fix - basically, we check to see if we have any valid keys, and don't run `kettle.loadTestingSupport()` or load the contract tests at all if we don't have any: https://github.com/waharnum/fluid-adaptive-content-service/blob/ba135c1faeaa0c2571eeefd3ca8684d4bfa529f3/share/translation/tests/translation-contract-tests.js

**Comment by kunal-mohta** [comment]
@waharnum Did you try this locally? Because I am facing the same error even after implementing this.

**Comment by kunal-mohta** [comment]
@waharnum Fixed this with your method. Thanks for the help!
