### ISSUE TITLE
Google Translation - Handle language codes with greater than 3 letters

### ISSUE THREAD

**Issue by kunal-mohta** [kunal-mohta/fluid-adaptive-content-service#2]
All the services involving language codes, have codes with number of letters less than or equal to 3. However Google has **two** language whose code has number of letters greater than 3.

**Language** - Chinese (Simplified)
**Code** - zh-CN

**Language** - Chinese (Traditional)
**Code** - zh-TW

How to handle these separatly is yet to be figured.

**Comment by waharnum** [comment]
Have a look at this and the linked sections: https://en.wikipedia.org/wiki/Language_localisation#Language_tags_and_codes

It should be safe to check that the language code consists of no more than seven characters.
